### ISSUE TITLE
Zarr example notebook on main branch not working

### ISSUE THREAD

**Issue by bnmajor** [InsightSoftwareConsortium/itkwidgets#460]
Running `open_group` in the [zarr notebook](https://github.com/InsightSoftwareConsortium/itkwidgets/blob/main/examples/integrations/zarr/OME-NGFF-Brainstem-MRI.ipynb) produces an error:
```
TypeError: __init__() got an unexpected keyword argument 'loop'
```

Produced by running the third cell:
```
fsstore = FSStore('https://dandiarchive.s3.amazonaws.com/zarr/7723d02f-1f71-4553-a7b0-47bda1ae8b42')
brainstem = zarr.open_group(fsstore, mode='r')
```

Full traceback:
```
Exception ignored in: <function ClientSession.__del__ at 0x7efeb46f1ca0>
Traceback (most recent call last):
  File "/home/local/KHQ/brianna.major/.virtualenvs/itkwidgets/lib/python3.8/site-packages/aiohttp/client.py", line 269, in __del__
    if not self.closed:
  File "/home/local/KHQ/brianna.major/.virtualenvs/itkwidgets/lib/python3.8/site-packages/aiohttp/client.py", line 894, in closed
    return self._connector is None or self._connector.closed
AttributeError: _connector
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [6], in <cell line: 2>()
      1 fsstore = FSStore('https://dandiarchive.s3.amazonaws.com/zarr/7723d02f-1f71-4553-a7b0-47bda1ae8b42')
----> 2 brainstem = zarr.open_group(fsstore, mode='r')

File ~/.virtualenvs/itkwidgets/lib/python3.8/site-packages/zarr/hierarchy.py:1344, in open_group(store, mode, cache_attrs, synchronizer, path, chunk_store, storage_options, zarr_version)
   1341 # ensure store is initialized
   1343 if mode in ['r', 'r+']:
-> 1344     if not contains_group(store, path=path):
   1345         if contains_array(store, path=path):
   1346             raise ContainsArrayError(path)

File ~/.virtualenvs/itkwidgets/lib/python3.8/site-packages/zarr/storage.py:116, in contains_group(store, path, explicit_only)
    114 store_version = getattr(store, '_store_version', 2)
    115 if store_version == 2 or explicit_only:
--> 116     return key in store
    117 else:
    118     if key in store:

File ~/.virtualenvs/itkwidgets/lib/python3.8/site-packages/zarr/storage.py:1413, in FSStore.__contains__(self, key)
   1411 def __contains__(self, key):
   1412     key = self._normalize_key(key)
-> 1413     return key in self.map

File ~/.virtualenvs/itkwidgets/lib/python3.8/site-packages/fsspec/mapping.py:174, in FSMap.__contains__(self, key)
    172 """Does key exist in mapping?"""
    173 path = self._key_to_str(key)
--> 174 return self.fs.exists(path) and self.fs.isfile(path)

File ~/.virtualenvs/itkwidgets/lib/python3.8/site-packages/fsspec/asyn.py:86, in sync_wrapper.<locals>.wrapper(*args, **kwargs)
     83 @functools.wraps(func)
     84 def wrapper(*args, **kwargs):
     85     self = obj or args[0]
---> 86     return sync(self.loop, func, *args, **kwargs)

File ~/.virtualenvs/itkwidgets/lib/python3.8/site-packages/fsspec/asyn.py:66, in sync(loop, func, timeout, *args, **kwargs)
     64     raise FSTimeoutError from return_result
     65 elif isinstance(return_result, BaseException):
---> 66     raise return_result
     67 else:
     68     return return_result

File ~/.virtualenvs/itkwidgets/lib/python3.8/site-packages/fsspec/asyn.py:26, in _runner(event, coro, result, timeout)
     24     coro = asyncio.wait_for(coro, timeout=timeout)
     25 try:
---> 26     result[0] = await coro
     27 except Exception as ex:
     28     result[0] = ex

File ~/.virtualenvs/itkwidgets/lib/python3.8/site-packages/fsspec/implementations/http.py:299, in HTTPFileSystem._exists(self, path, **kwargs)
    297 try:
    298     logger.debug(path)
--> 299     session = await self.set_session()
    300     r = await session.get(path, **kw)
    301     async with r:

File ~/.virtualenvs/itkwidgets/lib/python3.8/site-packages/fsspec/implementations/http.py:122, in HTTPFileSystem.set_session(self)
    120 async def set_session(self):
    121     if self._session is None:
--> 122         self._session = await self.get_client(loop=self.loop, **self.client_kwargs)
    123         if not self.asynchronous:
    124             weakref.finalize(self, self.close_session, self.loop, self._session)

File ~/.virtualenvs/itkwidgets/lib/python3.8/site-packages/fsspec/implementations/http.py:29, in get_client(**kwargs)
     28 async def get_client(**kwargs):
---> 29     return aiohttp.ClientSession(**kwargs)

TypeError: __init__() got an unexpected keyword argument 'loop'
```

**Comment by thewtex** [comment]
This may be the package version issue reference earlier? `aiohttp` may need to be uploaded or downgraded from pre-release.

**Comment by thewtex** [comment]
In #464 , we remove the `imjoy` dependency because we just need `imjoy_rpc` (@oeway please correct me if I am wrong on this). This remove `aiohttp` as a transitive dependency, which will address this (and support JupyterLite).

**Comment by oeway** [comment]
Yes, you only need imjoy_rpc
