### ISSUE TITLE
Divide by zero error with 2D 520x520 image

### ISSUE THREAD

**Issue by PaulHax** [InsightSoftwareConsortium/itkwidgets#554]
With a notebook like this
```
import sys
!{sys.executable} -m pip install -q "itkwidgets[notebook]>=1.0a15"

import numpy as np
from itkwidgets import view

points = np.random.uniform(high=100.0, size=(520,520)).astype(np.float32)

view(points)
```
Getting error in browser console
```
index.js:148 Traceback (most recent call last):
  File "/home/paul/src/itkwidgets/.venv/lib/python3.10/site-packages/imjoy_rpc/rpc.py", line 404, in _wait
    result = await result
  File "/home/paul/src/itkwidgets/.venv/lib/python3.10/site-packages/itkwidgets/viewer.py", line 87, in run
    result = _get_viewer_image(data, label=False)
  File "/home/paul/src/itkwidgets/.venv/lib/python3.10/site-packages/itkwidgets/integrations/__init__.py", line 126, in _get_viewer_image
    to_ngff_zarr(store, multiscales, chunk_store=chunk_store)
  File "/home/paul/src/itkwidgets/.venv/lib/python3.10/site-packages/ngff_zarr/to_ngff_zarr.py", line 61, in to_ngff_zarr
    arr = dask.array.to_zarr(
  File "/home/paul/src/itkwidgets/.venv/lib/python3.10/site-packages/dask/array/core.py", line 3700, in to_zarr
    return arr.store(z, lock=False, compute=compute, return_stored=return_stored)
  File "/home/paul/src/itkwidgets/.venv/lib/python3.10/site-packages/dask/array/core.py", line 1770, in store
    r = store([self], [target], **kwargs)
  File "/home/paul/src/itkwidgets/.venv/lib/python3.10/site-packages/dask/array/core.py", line 1226, in store
    store_dlyds = persist(*store_dlyds, **kwargs)
  File "/home/paul/src/itkwidgets/.venv/lib/python3.10/site-packages/dask/base.py", line 901, in persist
    results = schedule(dsk, keys, **kwargs)
  File "/home/paul/src/itkwidgets/.venv/lib/python3.10/site-packages/dask/threaded.py", line 89, in get
    results = get_async(
  File "/home/paul/src/itkwidgets/.venv/lib/python3.10/site-packages/dask/local.py", line 511, in get_async
    raise_exception(exc, tb)
  File "/home/paul/src/itkwidgets/.venv/lib/python3.10/site-packages/dask/local.py", line 319, in reraise
    raise exc
  File "/home/paul/src/itkwidgets/.venv/lib/python3.10/site-packages/dask/local.py", line 224, in execute_task
    result = _execute_task(task, data)
  File "/home/paul/src/itkwidgets/.venv/lib/python3.10/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/home/paul/src/itkwidgets/.venv/lib/python3.10/site-packages/dask/array/core.py", line 4372, in store_chunk
    return load_store_chunk(x, out, index, lock, return_stored, False)
  File "/home/paul/src/itkwidgets/.venv/lib/python3.10/site-packages/dask/array/core.py", line 4354, in load_store_chunk
    out[index] = x
  File "/home/paul/src/itkwidgets/.venv/lib/python3.10/site-packages/zarr/core.py", line 1353, in __setitem__
    self.set_basic_selection(pure_selection, value, fields=fields)
  File "/home/paul/src/itkwidgets/.venv/lib/python3.10/site-packages/zarr/core.py", line 1448, in set_basic_selection
    return self._set_basic_selection_nd(selection, value, fields=fields)
  File "/home/paul/src/itkwidgets/.venv/lib/python3.10/site-packages/zarr/core.py", line 1746, in _set_basic_selection_nd
    indexer = BasicIndexer(selection, self)
  File "/home/paul/src/itkwidgets/.venv/lib/python3.10/site-packages/zarr/indexing.py", line 342, in __init__
    dim_indexer = SliceDimIndexer(dim_sel, dim_len, dim_chunk_len)
  File "/home/paul/src/itkwidgets/.venv/lib/python3.10/site-packages/zarr/indexing.py", line 176, in __init__
    self.nchunks = ceildiv(self.dim_len, self.dim_chunk_len)
  File "/home/paul/src/itkwidgets/.venv/lib/python3.10/site-packages/zarr/indexing.py", line 160, in ceildiv
    return math.ceil(a / b)
ZeroDivisionError: division by zero
```
Notebook works with 519x519 image.

Reported here:
https://discourse.itk.org/t/itkwidgets-large-images/5401

**Comment by thewtex** [comment]
@PaulHax thanks for the report and the nice reproducible example.

Addressed in #562
