### ISSUE TITLE
Point set tools are not displayed

### ISSUE THREAD

**Issue by tbirdso** [InsightSoftwareConsortium/itkwidgets#605]
## Overview

When trying to view a point set in a scene by itself the individual points are very small. From conversation with @PaulHax it sounds like there are existing tools for adjusting point size that are intended to be displayed, but are not.

## Expected behavior

Tools are available to adjust point set size and possibly other details such as point color.

## Observed behavior

3D points are displayed, but no tool is given for adjusting point size. Default size is small, white points that are hard to see against light gray background.

![itkwidgets-no-point-set-tools](https://user-images.githubusercontent.com/40648863/214317472-5b1e4b75-da27-426b-be3a-21e81b3a28fc.png)

## Versions

itkwidgets==1.0a22
itk==5.3.0

## Other notes

- In the screenshot above, `type(input_points)` is `itk.itkPointSetPython.itkPointSetF3`
- Screenshots of landmark points in the [`ThinPlateSpline.ipynb` example notebook](https://github.com/bnmajor/itkwidgets/blob/c9ff7ed9fb073ca060bde2a15deba4367e029697/examples/integrations/itk/ThinPlateSpline.ipynb) on GitHub seem to show similar behavior.

**Comment by tbirdso** [comment]
The following error appears in the browser console when I run `itkwidgets.view(point_sets=input_points)` and may or may not be relevant:

```
mobx] Encountered an uncaught exception that was thrown by a reaction or observer component, in: 'Reaction[Reaction@10]' RangeError: Invalid typed array length: 16
    at new Float32Array (<anonymous>)
    at Object.buildArrays (index.js:138:19)
    at Object.getBounds (index.js:77:5)
    at Object.getBounds (index.js:75:5)
    at a (index.js:282:7)
    at Array.forEach (<anonymous>)
    at Object.getBounds (index.js:294:7)
    at ItkVtkViewProxy.js:269:27
    at Array.forEach (<anonymous>)
    at i (ItkVtkViewProxy.js:266:27)
```

**Comment by tbirdso** [comment]
cc @thewtex @PaulHax

**Comment by bnmajor** [comment]
@thewtex It looks like I may have been thinking of the reference-ui becuase it seems that the point set tools were [never implemented](https://github.com/InsightSoftwareConsortium/itk-viewer-bootstrap-ui/blob/main/src/PointSetInterface.jsx#L11) in the bootstrap-ui....

@tbirdso I will need to add these into the default bootstrap-ui but as a temporary workaround you can pass `ui-"reference"` into the viewer and the point set controls will be available

**Comment by tbirdso** [comment]
> as a temporary workaround you can pass ui-"reference" into the viewer and the point set controls will be available

Thanks @bnmajor , this works well for visualizing an individual point set.

![points-reference](https://user-images.githubusercontent.com/40648863/214362698-85ad6f75-907e-424a-81c8-e49ddba943a7.png)
